# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moritzzimmer/func/releases/download/v0.0.19/func_0.0.19_darwin_amd64.tar.gz"
    sha256 "ce2b26f5c0242059acf0e59e6c1528c25307f8412246b75406937882c76f3f90"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/moritzzimmer/func/releases/download/v0.0.19/func_0.0.19_linux_amd64.tar.gz"
    sha256 "31f09f4423717e658deeb0036de315a4919d50c6deb944752d4dc7e1aa0af21e"
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
