# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moritzzimmer/func/releases/download/v0.0.17/func_0.0.17_darwin_amd64.tar.gz"
    sha256 "acf4ee0070b10c0a0a9697adb67e17cc0dc4be7d13d93c271f1faad94ebbd266"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/moritzzimmer/func/releases/download/v0.0.17/func_0.0.17_linux_amd64.tar.gz"
      sha256 "1f6f4da984a9fd778ba80b87a0dc3222e8679dccf5ce99242ffad11d5aec3129"
    end
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
