# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moritzzimmer/func/releases/download/v0.0.12/func_0.0.12_darwin_amd64.tar.gz"
    sha256 "557af3073ff24851fd0ac06caacf4a141f8f5768124557eb9d016592ade4da80"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/moritzzimmer/func/releases/download/v0.0.12/func_0.0.12_linux_amd64.tar.gz"
      sha256 "c8001ce062702c4bc8df1c3434a9cab642fbe770677b375cc0f583ae66e17073"
    end
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
